### ISSUE TITLE
Battle for Azeroth PVP and PVE Milestones

### ISSUE THREAD

**Issue by JamesIves** [JamesIves/discord-wow-armory-bot#34]
As Battle for Azeroth nears release this bot needs to be updated with data from the new expansion, and data from the previous expansion needs to be removed. I'll be using this ticket here to track the progress.

**Comment by JamesIves** [comment]
All work for this release is being handled in the `bfa-beta` branch.

## Checklist
- [X] Add raid data for the first Tier, Uldir. 
- [x] Update the keystone master achievements to their new ids. 
- [X] Remove data related to the Mage Tower.
- [x] Add BFA PVE achievements.
- [ ] Add current honor level for PVP.
